name: Java CI with Maven - Test and package

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout du dépôt
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # nécessaire pour Maven et Sonar éventuellement

      # 2️⃣ Setup Java 21
      - name: Set up Java 21 (Corretto)
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: '21'

      # 3️⃣ Cache Maven
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4️⃣ Build Maven (tests inclus)
      - name: Build with Maven
        run: mvn -B package
        working-directory: ./tpintegrationcontinue-Hugo-Blaise  # chemin vers le dossier cloné
